### ISSUE TITLE
Missing sass and scss icons

### ISSUE THREAD

**Issue by rstraub** [JustSid/AfterglowIntelliJ#20]
Could you add the following icons for the .scss and .sass files? 

![file_type_scss](https://cloud.githubusercontent.com/assets/2283567/14733869/8c1eeec4-0866-11e6-83ab-95c970f03e30.png)
![file_type_scss 2x](https://cloud.githubusercontent.com/assets/2283567/14733870/8c2b250e-0866-11e6-9705-5e5d5c02fa76.png)

Thank you!

**Comment by JustSid** [comment]
Hey, sorry for the late reply. I'm currently working on a better theme engine that allows easily adding support for custom file icons. I was actually hoping I'd had it done by now, but alas real life got in the way as per the usual. Just wanted to let you know that I have seen the issue though :)

**Comment by mliq** [comment]
My .scss files show as generic gear icons now, it was working at some point but no more :(

If I put the registered pattern as `*.scss` it has the gear, if I do `?.scss`, it does purple horizontal lines. (I have only default file types otherwise, and the latest WebStorm).

Here is a screenshot:
<img width="492" alt="screenshot 2016-05-12 22 50 47" src="https://cloud.githubusercontent.com/assets/7573605/15237505/09c7bcf6-1894-11e6-9b7a-7c1875a188c4.png">

Thank you much, very nice work! Let me know if I can help you test or debug in any way.

**Comment by JustSid** [comment]
This is _finally_ fixed in 75d0810e3bfa8190409d303ba06ce55406d8758f, sorry for taking so long.

**Comment by gsouf** [comment]
Hi @JustSid  I just installed afterglow and scss files are appearing with a gear icon
