### ISSUE TITLE
Does not work with PHPStorm 10.0.3

### ISSUE THREAD

**Issue by tmpjr** [JustSid/AfterglowIntelliJ#8]
When going to File > Import Settings and selecting the jar I get the following error:

"Invalid File"

"The file 'AfterglowTheme.jar' contains no settings to import. Please make sure you have generated the file using 'File|Export Settings' feature.

OS X Yosemite 10.10.4

Is there another way to install it? I tried installing through the plugin manager but it does not show up in the Appearance:Theme dropdown.

Thanks!

**Comment by JustSid** [comment]
You install the plugin through the plugin dialogues in the settings, either by clicking on "Install plugin from disk" where you can then select the `.jar` file or by installing it through the JetBrains plugin repository by clicking on "Browse repositories" and then searching for `Afterglow Theme`.

If it's in the plugin list, you are golden! It's not actually a Theme in the sense of the themes IntelliJ provides, since there is not really a plugin mechanism for these, but rather it "hacks" the Darcular theme with some additional icons and changes of the sidebar colour. So it should just work once you have the plugin installed. I haven't tested it with PHPStorm though, so if you have it installed and can't see anything, let me know and I'll re-open the issue and see what I can do.
